### PR TITLE
Add wg-profile-guided-optimization.

### PR DESCRIPTION
**Pull request by michaelwoerister**

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc @davidtwco @nikomatsakis

**Comment by michaelwoerister** [comment]
@rust-lang/compiler What's the policy on merging PRs in this repo? Do we merge ourselves once the PR is approved?

**Comment by nikomatsakis** [comment]
@michaelwoerister I think it's fine to merge yourself if you feel like consensus is achieved.

**Comment by nikomatsakis** [comment]
That said, I did this one.

**Comment by michaelwoerister** [comment]
:+1:

**Pull request merged**
