### PR TITLE
Add missing grammar directory to experts map

### PR DESCRIPTION
**Pull request by spastorino**
This is part of #87, would be nice if others can jump in and suggest missing parts too :).

### CODE REVIEW

**Comment by igaray** [comment]
Just noticed that the 'miri' entry has a duplicated folder `"src/librustc/mir/interpret"`

**Comment by spastorino** [comment]
@igaray 
```
"src/librustc/mir/interpret",
"src/librustc_mir/interpret",
```

Note the `/` and `_` between `librustc` and `mir`

**Comment by igaray** [comment]
Ha, tricky, I swear I looked three times. 😅 Nvm!

**Comment by davidtwco** [comment]
Merging after discussion at meta working group meeting.

**Pull request merged**
