### PR TITLE
Add notes for triage meeting 2019-04-25

### PR DESCRIPTION
**Pull request by wesleywiser**
cc @nikomatsakis 

Are there issues you'd like me to mention in the "Volunteers wanted" section?

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@wesleywiser I have some notes on that, actually--

**Comment by nikomatsakis** [comment]
Hmm, not as complete as I might've liked, but I have

- Needs somebody to reduce rust-lang/rust#60136
- Needs somebody to write documentation rust-lang/rust#60059

**Comment by nikomatsakis** [comment]
Maybe we can add some brief notes for now?

**Comment by wesleywiser** [comment]
How's that?

**Comment by nikomatsakis** [comment]
Great!

**Comment by lqd** [comment]
just a note that I had already [reduced](https://github.com/rust-lang/rust/issues/60136#issuecomment-486712219) #60136 :)

**Pull request merged**
