### PR TITLE
[WIP] Create static web page for the compiler team with zola

### PR DESCRIPTION
**Pull request by unbalancedparentheses**
I am creating a static web page for the compiler team using [zola](https://github.com/getzola/zola). I should have a basic version working this week.

### CODE REVIEW

**Comment by davidtwco** [comment]
Thanks for doing this! I can't test it locally because you haven't included the `.gitmodules` file and therefore I can't run `git submodule update --init` to clone the `even` theme that you've included as a submodule.

**Comment by davidtwco** [comment]
Also, the infrastructure team have been writing up some static website procedures for rust-lang websites, [you can find those here](https://github.com/rust-lang/infra-team/blob/static-websites/guidelines/static-websites.md).

I'm not familiar with them, so I don't know what would need changed if anything, cc @shepmaster and @pietroalbini.

**Comment by unbalancedparentheses** [comment]
@davidtwco I still need to modify all the files to add have a header/front matter. Also I still need to fix the even submodule problem. I am not sure if the best thing is to include it as a submodule or directly include the code as part of the repo since I will need to change it quite a bit. 

Thanks for the link to the infra link, I will check it.

**Comment by pietroalbini** [comment]
Our infra guidelines are mostly for rust-lang.org subdomains, while I guess this will be hosted directly on github.io. Still, we'd prefer if this repo used the deploy keys tooling we built -- ping me when you have a `.travis.yml` and I'll set it up.

**Comment by unbalancedparentheses** [comment]
Tasks left:
- add removed files by mistake
- manually add title to all documents and dates to all files
- add links between files
- only entries from a blog folder should be added to the blog index that sits at the root. i don't know why some entries are being added by zola automatically.

**Comment by unbalancedparentheses** [comment]
Sorry for the delay, I am having a rough month. I will work on this tonight

**Comment by unbalancedparentheses** [comment]
Yesterday I fighted against zola. I don't have the time and web skills to create a good theme for zola.

I migrated everything to hugo where I already have selected a great theme that has blog + documentation and things are looking fine. Should be able to push a basic version it in a few days.

**Comment by unbalancedparentheses** [comment]
Done! What do you think?
Screenshot_2019-06-06 Introduction Rust Lang - Compiler Team

I will upload the PR so that you can review it.

**Comment by unbalancedparentheses** [comment]
I need to update the root link, but here you can at least view the index:
https://unbalancedparentheses.github.io/compiler-team/

**Pull request closed without merging**
