### PR TITLE
Remove experts map

### PR DESCRIPTION
**Pull request by spastorino**
r? @davidtwco

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
Can you update the expert map to reflect this too @spastorino?

**Comment by spastorino** [comment]
> Can you update the expert map to reflect this too @spastorino?

Sorry, I may be missing something. Which expert map are you referring to?

**Comment by lqd** [comment]
Did you mean the dev guide david? https://rustc-dev-guide.rust-lang.org/#experts

**Comment by spastorino** [comment]
Yeah, I've left a comment in the dev guide issue that originated this that we need to fix the dev guide.

**Comment by spastorino** [comment]
Created this https://github.com/rust-lang/rustc-dev-guide/pull/1831

**Comment by davidtwco** [comment]
I did mean the dev guide, oops.

**Pull request merged**
