### PR TITLE
Fix WGs information and rotation

### PR DESCRIPTION
**Pull request by spastorino**
I'm not sure if LLVM (currently says Incubating) (cc @nagisa), RFC 2229 (currently says Paused until 2020) (cc @blitzerr @nikomatsakis) and Polymorphization (cc @nikomatsakis @davidtwco) are active, I think Polymorphization is but unsure the rest.

Another thing is that I've re-sorted the rotation, that may make some checkins to repeat sooner than expected but I guess is nice to match the same order we have on the landing page for easier syncronization between both. Anyway unsure if current order was in the way it was for some particular reason. cc @pnkfelix

### CODE REVIEW

**Comment by davidtwco** [comment]
Polymorphisation is active, just slow going. 😀

**Comment by spastorino** [comment]
I guess the only pending question now is if it's ok the re-sorting I've done to the list. cc @pnkfelix

**Comment by pnkfelix** [comment]
It looks to me like the old order was roughly alphabetical, and then someone added Polymorphisation to the end?

I was not able to infer what order you have applied here in this PR.

I don't have an attachment to any particular ordering. If we have to choose a fixed order, then alphabetical is fine. But we can also just add things randomly, I don't think it matters much.

**Comment by spastorino** [comment]
Sorted both lists alphabetically so it's easier and kind of keeps old order.

**Pull request merged**
