### PR TITLE
Fix license paths

### PR DESCRIPTION
**Pull request by Zopolis4**
Should work in theory, I haven't tested locally.

### CODE REVIEW

**Comment by bjorn3** [comment]
This won't work for the rendered version on https://rust-lang.github.io.

**Comment by Zopolis4** [comment]
What's the issue? It looks like valid markdown pathing to me.

**Comment by bjorn3** [comment]
Sure, but the files are simply absent in the rendered version. You did need a full link like https://github.com/rust-lang/compiler-team/blob/master/LICENSE-MIT rather than a relative link like ../LICENSE-MIT for them to resolve on the site.

**Comment by Zopolis4** [comment]
Fixed, hopefully.

**Review by bjorn3 — APPROVED** [review]

**Pull request merged**
