### PR TITLE
Update Rustdoc section and add bootstrap

### PR DESCRIPTION
**Pull request by jyn514**
cc @Mark-Simulacrum, @ehuss - do the 'familiar' and 'experts' sections look right? Did I miss anyone?

### CODE REVIEW

**Comment by ehuss** [comment]
I'm fine with adding my name, though I don't know what consequence it has.

**Comment by jyn514** [comment]
@ehuss AFAIK, it's mostly so people know who to ask for help on Zulip. I don't know any tools that parse this.

**Comment by LeSeulArtichaut** [comment]
Maybe WG-Meta can help? cc @spastorino

**Comment by spastorino** [comment]
Currently it's just informative, no consequences at all.

**Comment by camelid** [comment]
Seems like this can be merged?

**Pull request merged**
