### PR TITLE
Update wg status

### PR DESCRIPTION
**Pull request by apiraino**
- [x] updated the status of the various WG according to what the [main page](https://rust-lang.github.io/compiler-team/) actually says (WG-meta set to `paused`)

- [x] assigned a consistent color scheme:
  - green: wg active
  - yellow: wg incubating or paused
  - red: wg retired

- [x] remove WG-meta from checkin rotation

### CODE REVIEW

**Comment by apiraino** [comment]
@spastorino here is the proposed patch to remove the Wg-meta from the checkin scheduling.

I've slightly rearranged in commit b31afa0 the WG order in order to respect the current schedule that appear from the master branch. I've tested in my local environment, also by faking the current date with
`var today = new Date('13 Feb 2021 16:00:00 UTC');`
and it looks this patch still respects the current rotation.

I also took the liberty of setting the WG status for a couple of "leaf" pages that were not consistent with the main WG page

wdy? Let me know if you spot anything weird.

thanks!

**Comment by wesleywiser** [comment]
This looks great to me! My only comment is that red is often often used to indicate danger and (IMO) has some negative connotations especially when in used in a green/yellow/red color scheme. I would recommend using a more neutral color for the retired groups. Some kind of grey might be a good choice as these groups are completely inactive.

**Comment by spastorino** [comment]
@apiraino this is fine to me, as soon as you address @wesleywiser concerns I could merge it.

**Comment by apiraino** [comment]
yup, just commited @spastorino.

do you prefer I rebase into a single branch before merging?

**Pull request merged**
